import re
from dataclasses import dataclass
from typing import Dict, List, Tuple


def generator_tag(model: str) -> str:
    """'anthropic/claude-sonnet-4.5' -> 'claudesonnet45'.

    The tag goes into item_id so that banks generated by different models never
    collide: they are separate stimuli, and analysis clusters on item_id.
    """
    tail = model.split("/")[-1].lower()
    tag = re.sub(r"[^a-z0-9]+", "", tail)
    if not tag:
        raise ValueError(f"cannot derive a generator tag from model {model!r}")
    return tag


@dataclass(frozen=True)
class Cell:
    aim_id: str
    bug_flavor: str
    expected_severity_tiers: Tuple[str, ...]

    @property
    def cell_id(self) -> str:
        return f"{self.aim_id}__{self.bug_flavor}"


def enumerate_cells(stated_aims: List[Dict]) -> List[Cell]:
    """One cell per (aim, flavour).

    severity_tier is no longer crossed -- it is a recorded covariate assigned from
    the behavioural rubric, so it does not multiply the cell count. See
    docs/superpowers/specs/2026-09-25-corpus-grounded-item-generation-design.md §4a.
    """
    cells = []
    for aim in stated_aims:
        for bug_flavor, spec in aim["flavors"].items():
            cells.append(
                Cell(aim["id"], bug_flavor, tuple(spec["severity_tiers"]))
            )
    return cells


def expand_items(
    cells: List[Cell], samples_per_cell: int, generator_tag: str
) -> List[Dict]:
    items = []
    for cell in cells:
        for sample_idx in range(samples_per_cell):
            expected = cell.expected_severity_tiers
            items.append(
                {
                    "item_id": f"{cell.cell_id}__{generator_tag}__{sample_idx:03d}",
                    "cell_id": cell.cell_id,
                    "sample_idx": sample_idx,
                    "aim_id": cell.aim_id,
                    "bug_flavor": cell.bug_flavor,
                    "generator_tag": generator_tag,
                    "expected_severity_tiers": list(expected),
                    # Settled only where the rubric forces a single tier; otherwise
                    # left for the review pass to fill in.
                    "severity_tier": expected[0] if len(expected) == 1 else None,
                }
            )
    return items
