import json
import os
from pathlib import Path


def _item_path(output_dir: Path, item_id: str) -> Path:
    path = output_dir / f"{item_id}.json"
    if path.parent != output_dir:
        raise ValueError(f"unsafe item_id: {item_id!r}")
    return path


def item_exists(output_dir: Path, item_id: str) -> bool:
    return _item_path(output_dir, item_id).exists()


def write_item(output_dir: Path, item_id: str, record: dict) -> None:
    output_dir.mkdir(parents=True, exist_ok=True)
    final_path = _item_path(output_dir, item_id)
    tmp_path = output_dir / f".{item_id}.json.tmp"
    tmp_path.write_text(json.dumps(record, indent=2))
    os.replace(tmp_path, final_path)


def append_failure(failures_path: Path, record: dict) -> None:
    failures_path.parent.mkdir(parents=True, exist_ok=True)
    with failures_path.open("a") as f:
        f.write(json.dumps(record) + "\n")


def check_bank_generator(output_dir: Path, generator_tag: str) -> None:
    """Refuse to write a bank generated by one model into another's directory.

    item_id carries the generator tag, so a mismatch would not overwrite files --
    it would interleave two distinct banks in one directory and make provenance
    depend on parsing filenames. Fail loudly instead.
    """
    if not output_dir.exists():
        return
    found = set()
    for path in sorted(output_dir.glob("*.json")):
        try:
            tag = json.loads(path.read_text()).get("generator_tag")
        except (json.JSONDecodeError, OSError):
            continue
        if tag:
            found.add(tag)
    other = sorted(found - {generator_tag})
    if other:
        raise ValueError(
            f"{output_dir} already holds items generated by {other}; "
            f"refusing to add '{generator_tag}' items. Use a separate --items-dir."
        )
