#!/usr/bin/env python3
"""Exploratory probe of the generator-model confound (design.md 6.2 territory).

Every wave-1 item was generated by claude-sonnet-4.5, so for a Claude judge the
`self` label is approximately TRUE while every other label is false. That makes
"self-preference" and "label happens to be accurate" observationally equivalent
in the headline H3 result -- unless we use the rival rotation: GPT-5 judges were
told "written by Claude" on 108 rows, which is the truthful label for a judge
that is not Claude.

The contrast below is therefore *within* the other-model condition and *within*
judge, so it is not confounded with self-vs-other:

    for GPT-5 judges only: truthful rival label (claude) vs. false rival labels
    (gemini, llama), on otherwise identical items.

If label truth drives the effect, this contrast should move. If it is flat, the
self-preference reading survives this particular challenge. Underpowered either
way -- this is a direction-check, not a test.
"""
import sys
from pathlib import Path

import numpy as np
import pandas as pd

sys.path.insert(0, str(Path(__file__).resolve().parent))
from frame import HYPOTHESES, load_frame  # noqa: E402
from wcb import wcb_test  # noqa: E402


def main():
    df = load_frame()
    df = df[(df["code_version"] == "buggy") & df["author_label"].isin(["other_model_A", "other_model_B"])]

    print("\nGENERATOR-MODEL CONFOUND PROBE (exploratory, uncorrected)")
    print("Within rival labels only: truthful rival vs. false rival, per judge.\n")
    print(f"{'judge':18s}{'question':20s}{'n_true':>7s}{'n_false':>8s}"
          f"{'mean_T':>8s}{'mean_F':>8s}{'diff':>7s}{'p_wcb':>8s}")

    rows = []
    for question in HYPOTHESES.values():
        for cell, sub in df[df["question_type"] == question].groupby("judge_cell"):
            sub = sub.dropna(subset=["scale_response"]).sort_values("item_id")
            truth = sub["label_is_true"].astype("boolean")
            if truth.sum() == 0 or (~truth.fillna(False)).sum() == 0:
                print(f"{cell:18s}{question:20s}{'-':>7s}{'-':>8s}"
                      f"{'':>8s}{'':>8s}{'':>7s}{'no variance':>12s}")
                continue
            t = truth.fillna(False).to_numpy(dtype=float)
            y = sub["scale_response"].to_numpy(dtype=float)
            X = np.column_stack([np.ones(len(sub)), t])
            beta, se, tstat, p = wcb_test(y, X, sub["item_id"].to_numpy(), 1,
                                          n_boot=4999, seed=20260924)
            mt, mf = y[t == 1].mean(), y[t == 0].mean()
            print(f"{cell:18s}{question:20s}{int(t.sum()):>7d}{int((1-t).sum()):>8d}"
                  f"{mt:>8.2f}{mf:>8.2f}{beta:>7.2f}{p:>8.4f}")
            rows.append(dict(judge_cell=cell, question=question, n_true=int(t.sum()),
                             n_false=int((1 - t).sum()), mean_true=mt, mean_false=mf,
                             estimate=beta, se=se, p_raw=p))

    print("\nOnly GPT-5 has variance here: Claude judges never saw a truthful rival label,")
    print("because the rival pool excludes the judge's own family by construction.")
    out = Path(__file__).resolve().parent / "truth_diagnostic.csv"
    pd.DataFrame(rows).to_csv(out, index=False)
    print(f"\nwrote {out}")


if __name__ == "__main__":
    main()
